postgres:
  image: postgres:latest
  environment:
    POSTGRES_DB: fjam
    POSTGRES_USER: fjam
    POSTGRES_PASSWORD: fjam
    PGDATA: /data
  ports:
    - "5432:5432"
  restart: always
  volumes:
    - "/var/www/fjam_data/pg/db:/data"
