[package]
name = "convert"
version = "0.1.0"
authors = ["Andriy Kovalov <andy.kovv@gmail.com>"]
edition = "2018"

[dependencies]

convert-derive = { path = "../convert-derive" }

serde = "1"
serde_json = "1.0"
serde_derive = "1"
rmp-serde = "0.13.7"